
services:
  server:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/server
    restart: unless-stopped
    networks:
      - caddy
      - internal
    volumes:
      - ./:/eve-incursions
    environment:
      - PGHOST
      - PGUSER
      - PGPASSWORD
      - PGDATABASE

  ws:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/ws
    restart: unless-stopped
    networks:
      - internal
      - caddy
    volumes:
      - ./:/eve-incursions

  frontend:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/frontend
    restart: unless-stopped
    networks:
      - caddy
      - internal
    volumes:
      - ./:/eve-incursions

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - eve-incursions-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
    networks:
      - internal
    ports:
      - 5433:5432

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal


volumes:
  eve-incursions-pg-data:

networks:
  caddy:
    external: true
  internal:
